### ISSUE TITLE
Adding sphinx autodoc broke the build on Ubuntu 20.04 focal

### ISSUE THREAD

**Issue by mbanck** [zalando/patroni#2934]
### What happened?

3.2.0 no longer builds on focal:

https://pgdgbuild.dus.dg-i.net/job/patroni-binaries/222/architecture=amd64,distribution=focal/console#console-section-5

```
01:09:49 reading sources... [ 20%] modules/patroni
01:09:49 
01:09:49 Exception occurred:
01:09:49   File "/usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py", line 82, in members_option
01:09:49     return [x.strip() for x in arg.split(',')]
01:09:49 AttributeError: 'bool' object has no attribute 'split'
01:09:49 The full traceback has been saved in /tmp/sphinx-err-qki21gpq.log, if you want to report the issue to the developers.
01:09:49 Please also report this if it was a user error, so that a better error message can be provided next time.
01:09:49 A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
01:09:50 make[2]: *** [Makefile:20: html] Error 2
```

### How can we reproduce it (as minimally and precisely as possible)?

Run `(cd docs; $(MAKE) html)` on Ubuntu 20.04 focal

### What did you expect to happen?

Build succeeds

### Patroni/PostgreSQL/DCS version

-   Patroni version: 3.2.0
-   PostgreSQL version:  n/a
-   DCS (and its version): n/a

### Patroni configuration file

```yaml
n/a
```

### patronictl show-config

```yaml
n/a
```

### Patroni log files

```shell
n/a
```

### PostgreSQL log files

```shell
n/a
```

### Have you tried to use GitHub issue search?

- [X] Yes

**Comment by mbanck** [comment]
I tried to much around a bit with the autodoc settings in `docs/conf.py` (after looking at https://github.com/sphinx-doc/sphinx/issues/8143), but without any luck so far.

Is focal still supported by the Patroni project?

**Comment by CyberDem0n** [comment]
According to https://github.com/sphinx-doc/sphinx/pull/6053 we can change `True` to `None` and it should work:
```diff
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -56,7 +56,7 @@ apidoc_separate_modules = True
 
 # Include autodoc for all members, including private ones and the ones that are missing a docstring.
 autodoc_default_options = {
-    "members": True,
+    "members": None,
     "undoc-members": True,
     "private-members": True,
 }
```

**Comment by mbanck** [comment]
Indeed that worked, thanks!
